### ISSUE TITLE
Maybe add Hydra as default?

### ISSUE THREAD

**Issue by sdat2** [ai4er-cdt/ai4er-cookiecutter#12]
Hydra seemed so cool. Maybe add it as default. I realise this is a bit opinionated.

**Comment by herbiebradley** [comment]
I'm sure you can guess what my opinion on this is :D but I'll leave it up to Simon M since this is essentially his repo.

**Comment by sdat2** [comment]
haha yeah, that presentation was too persuasive.

**Comment by Croydon-Brixton** [comment]
@herbiebradley I think it'd be great to include Hydra - feel free to just do so, I'm happy for this to be a collaboration and you definitely know best how to integrate it into the project

**Comment by herbiebradley** [comment]
Done in 08f6f4171091befae97e10779f9e2de4c68b9860
