### ISSUE TITLE
Suggested command to activate environment fails

### ISSUE THREAD

**Issue by DanJonesOcean** [ai4er-cdt/ai4er-cookiecutter#13]
Hello,

I am trying to use the ai4er-cookiecutter to make a new repository following the command-line approach. I followed the instructions to create a conda environment:
```
conda env create --prefix=./env -f requirements/environment.yml
```
which seemed to work okay. The setup script then suggested this command:
```
>>> New conda env created. Activate from project directory with:
conda activate ./env
```
However, this command returns an error:
```
conda activate ./env
-bash: syntax error near unexpected token `('
-bash: syntax error near unexpected token `('
```
I did some quick Googling, but I didn't find a solution. FYI: I'm using bash on a MacBook, via the terminal.

**Comment by sdat2** [comment]
Ah ok, I get this issue too. I think that it is a problem with your `.bashrc` file. The environment is still loading, but it won't be displayed on the terminal command line as active.

**Comment by DanJonesOcean** [comment]
Ah, that's too bad.

In any case, I've been trying to get into containers lately, which sidesteps the entire issue of fixing a broken/incomplete computing environment!
